### ISSUE TITLE
No module named 'gec.data'

### ISSUE THREAD

**Issue by canghaiyunfan** [Jacob-Zhou/gecdi#2]
ModuleNotFoundError: No module named 'gec.data'

**Comment by Jacob-Zhou** [comment]
Thank you for your report for this issue and I‘m sincerely sorry for my late reply.

This Error is caused by the `gec/data.py` has been mistakenly ignored by `.gitignore` file and was **fixed** in the latest version just now.

I am very very sorry for this mistake and the inconvenience caused to you.
If you have any other questions, please feel free to contact me.
